= yamltotable

yamlファイルの中身をmarkdownやasciidocのtabbler形式にパースする


== How to use

....
./y2tb.sh <target yml file>
....

=== requirements

* python 3.6.3
* plz install requirements.txt

....
pip install -r requirements.txt
....

=== options

....
usage: run.py [-h] [-o OUTPUT] [-md | -ad | --csv] yml_file

convert yaml file into tabular text(csv, markdown, AsciiDoc)

positional arguments:
  yml_file              target yaml file to convert

optional arguments:
  -h, --help            show this help message and exit
  -o OUTPUT, --output OUTPUT
                        output file name. If no designation, replace file
                        extension following table style
  -md, --markdown       as markdown style
  -ad, --asciidoc       as AsciiDoc style
  --csv                 as csv style
....

=== example

....
./y2tb example/test.yml  # default convert into markdown style
....

-> link:example/test.md[test.md]

....
./y2tb example/test2.yml -ad  # AsciiDoc style also supported
....

-> link:example/test2.adoc[test2.adoc]